Evaluate experimental design using D-Efficiency.

**Definitions**:

$\mathbf{X}$ is the model matrix: A row for each run and a column for each term in the model.

For instance, a model assuming only main effects:

$\mathbf{Y} = \mathbf{X} \beta + \alpha$

$\mathbf{X}$ will contain $p = m + 1$ columns (number of factors + intercept).


D-optimality:


*D-efficiency* $=  \left(\frac{1}{n}|\mathbf{X}'\mathbf{X}|^{1/p}\right)$

**D-efficiency**

D-efficiency compares the design $\mathbf{X}$ with the D-optmial design $\mathbf{X_D}$ for the assumed model: 

*D-efficiency* $= \left[ \frac{|\mathbf{X}'\mathbf{X}|}{|\mathbf{X_D}'\mathbf{X_D}|} \right]^{1/p}$


In JMP, the D-efficiency compares the design with an orthogonal design in terms of D-optimality criterion:

*D-efficiency* $= 100 \left(\frac{1}{n}|\mathbf{X}'\mathbf{X}|^{1/p}\right)$

**Designs**

D-optimal designs maximize $D$:

$D  = |\mathbf{X}'\mathbf{X}|$

(no need for the other terms because they are constant)

D-optimal split-plot designs maximize:

$D  = |\mathbf{X}'\mathbf{V}^{-1}\mathbf{X}|$

where $\mathbf{V}^{-1}$ is the block diagonal covariance matrix of the responses.

Split-plot designs are those that some factors are harder to vary than others. The covariance indiciates the ratio between the whole variance and the subplot variance to the error variance. 

**Estimation efficiency**

There are several parameters (see JMP guide), but they are related. The basic is the relateive std error to estimate, i.e., how large the standard errors of the model's parameter estimates are relative to the error standard deviation.

*SE* $= \sqrt{\left(\mathbf{X}'\mathbf{X}\right)_{ii}^{-1}}$

where $\left(\mathbf{X}'\mathbf{X}\right)_{ii}^{-1}$ is the $i$ diagonal of $\left(\mathbf{X}'\mathbf{X}\right)^{-1}$.

# Example

An example for 2-factor model with main effects:

In [1]:
import numpy as np

In [2]:
X1 = np.matrix( "[1 1 1; 1 -1 1; 1 -1 -1]")
X1

In [108]:
def Deff(X):
    # D-efficiency
    return 100.0/X1.shape[0] * ( np.linalg.det( np.dot( np.transpose( X ), X ) )**(1.0/X1.shape[1]))
def Dopt(X):
    # D-optimality
    return np.linalg.det( np.dot( np.transpose( X ), X ) )
def SE(X):
    # Estimation efficiency
    return np.diag( np.linalg.inv( np.dot( np.transpose( X ), X ) ) )
def Contrib(X):
    cn = []
    for i in range(0, X.shape[0]):
        cn.append( Dopt( np.vstack( [X[:i,:], X[i:,:]]  )  ) )
    return cn
    

In [107]:
Dopt( np.vstack( [X[:i,:], X[i:,:]]  )   )

-8.881784197001202e-14

In [109]:
Contrib(X1)

[-8.881784197001202e-14,
 -8.881784197001202e-14,
 -8.881784197001202e-14,
 -8.881784197001202e-14,
 -8.881784197001202e-14,
 -8.881784197001202e-14,
 -8.881784197001202e-14,
 -8.881784197001202e-14,
 -8.881784197001202e-14,
 -8.881784197001202e-14]

In [13]:
SE(X1)

array([0.5, 0.5, 0.5])

# Algorithm

In [160]:
p = 5 # Number of factors
n = 10 # Number of runs
# Initial design
X = np.random.randint(0,2,(n,p+1))
J = 0
w = 0
while ( (J < 1e4) and (w < 100) ):
    d2 = None
    d6 = None
    w += 1
    try:
        d1 = Deff( X )
        d2 = Dopt( X )
        d3 = SE( X )
        d4 = Contrib( X )
    except:
        continue
    J = max(J, d2)
    i = np.argmin( d4 )
    j = np.argmax( d3 )
    X1 = X
 
    if X[i,j] == 0:
        X1[i,j] = 1
    else:
        X1[i,j] = 0
    try:
        d5 = Deff( X1 )
        d6 = Dopt( X1 )
        d7 = SE( X1 )
        d8 = Contrib( X1 )
  
    except:
        continue
    if d6 > d2:
        X = X1
        print(w,J,d1,d2,d6,i,j)
    
    

1 69.00000000000001 20.252323149955778 69.00000000000001 192.0 0 4
2 192.0 24.018739103520055 192.0 311.9999999999998 0 1
4 311.9999999999998 21.720253176048686 104.99999999999987 311.9999999999998 0 4
6 311.9999999999998 21.720253176048686 104.99999999999987 311.9999999999998 0 4
8 311.9999999999998 21.720253176048686 104.99999999999987 311.9999999999998 0 4
10 311.9999999999998 21.720253176048686 104.99999999999987 311.9999999999998 0 4
12 311.9999999999998 21.720253176048686 104.99999999999987 311.9999999999998 0 4
14 311.9999999999998 21.720253176048686 104.99999999999987 311.9999999999998 0 4
16 311.9999999999998 21.720253176048686 104.99999999999987 311.9999999999998 0 4
18 311.9999999999998 21.720253176048686 104.99999999999987 311.9999999999998 0 4
20 311.9999999999998 21.720253176048686 104.99999999999987 311.9999999999998 0 4
22 311.9999999999998 21.720253176048686 104.99999999999987 311.9999999999998 0 4
24 311.9999999999998 21.720253176048686 104.99999999999987 311.99999999

In [155]:
Dopt(X)

125.99999999999989

In [161]:
(d2, d6)

(104.99999999999987, 311.9999999999998)

In [56]:
 np.dot( np.transpose( X), np.array( X ) ) 

array([[2, 0, 1, 2],
       [0, 0, 0, 0],
       [1, 0, 1, 1],
       [2, 0, 1, 2]])

In [36]:
np.transpose( X )

array([[1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
        0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
        1, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1],
       [1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
        0, 1],
       [0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
        1, 0],
       [1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
        1, 1],
       [1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
        1, 0],
       [1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
        1, 1],
       [1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
        0, 0],
       [0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 0],
       [0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 0]])

In [31]:
X

array([[1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0],
       [1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0],
       [1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0],
       [1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0],
       [1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0],
       [0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 0, 1, 0, 1, 0,